@jwt=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTE3Njg1MTR9.YUtsMGp4IX9YMIIzEdvm9vPpVo0nyQCFoX6nePlVGr0


### STUDENTS INDEX ###
GET http://localhost:3000/students.json

### STUDETS SHOW ###
GET http://localhost:3000/students.json

### STUDENTS CREATE
POST http://localhost:3000/students.json
Content-Type: application/json

{
  "first_name": "",
  "last_name": "",
  "email": "",
  "phone_number": "",
  "short_bio": "",
  "linkedin_url": "",
  "twitter_handle": "",
  "website_url": "",
  "online_resume_url": "",
  "github_url": "",
  "phone_number": "" 
}
### STUDENTS UPDATE ###
PATCH http://localhost:3000/students/2.json
Content-Type: application/json

{
  "first_name": "A name"
}
### STUDENTS DESTROY ###
DELETE http://localhost:3000/students/2.json

# ----------------------------------------------------------- #

### CAPSTONE INDEX ###
GET http://localhost:3000/capstones.json

### CAPSTONE SHOW ###
GET http://localhost:3000/capstones.json

### CAPSTONE CREATE
POST http://localhost:3000/capstones.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "",
  "description": "",
  "url": "",
  "screenshot": "",
}

### CAPSTONE UPDATE ###
PATCH http://localhost:3000/capstones/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{

}

### CAPSTONE DESTROY ###
DELETE http://localhost:3000/capstones/1
Authorization: Bearer {{jwt}}

# ----------------------------------------------------------- #

### EDUCATION INDEX ###
GET http://localhost:3000/educations.json

### EDUCATION SHOW ###
GET http://localhost:3000/educations.json

### EDUCATION CREATE
POST http://localhost:3000/educations.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "start_date": "",
  "end_date": "",
  "degree": "",
  "university_name": "",
  "details": ""
}
### EDUCATION UPDATE ###
PATCH http://localhost:3000/educations/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "degree": ""
}

### EDUCATION DESTROY ###
DELETE http://localhost:3000/educations/1.json
Authorization: Bearer {{jwt}}

# ----------------------------------------------------------- #

### EXPERIENCE INDEX ###
GET http://localhost:3000/experience.json

### EXPERIENCE SHOW ###
GET http://localhost:3000/experience.json

### EXPERIENCE CREATE
POST http://localhost:3000/experience.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "start_date": "",
  "end_date": "",
  "job_title": "",
  "company_name": "",
  "details": ""
}
### EXPERIENCE UPDATE ###
PATCH http://localhost:3000/experience/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "job_title": "Weee"
}

### EXPERIENCE DESTROY ###
DELETE http://localhost:3000/experience/1.json
Authorization: Bearer {{jwt}}

# ----------------------------------------------------------- #

### SKILLS INDEX ###
GET http://localhost:3000/skills.json

### SKILLS SHOW ###
GET http://localhost:3000/skills/1.json

### SKILLS CREATE
POST http://localhost:3000/skills.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
 "skill_name": "Ruby on Rails"
}
### SKILLS UPDATE ###
PATCH http://localhost:3000/skills/1.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{

}

### SKILLS DESTROY ###
DELETE http://localhost:3000/skills/1.json
Authorization: Bearer {{jwt}}

# ----------------------------------------------------------- #

### SESSION CREATE (login) ###
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test3@test.com",
  "password": "password"
}

### USERS CREATE (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test",
  "email": "test3@test.com",
  "password": "password",
  "password_confirmation": "password"
}


